### ISSUE TITLE
[hax]Documentation and Questions

### ISSUE THREAD

**Issue by starryeyez024** [elmsln/lrnwebcomponents#103]
This is a catch-all issue for the moment, to capture things I would like to know.  Either by virtue of pointing me at a doc, or fodder for maybe discussing at some kind of conference. :)

1. What kind of format should web component schemas have so that HAX can interact with them?
2. Is there any plan to create a component whose job it is to surface available custom properties (CSS variables) and allow editors to adjust them per page? 
3. Is there a document or video that walks through how HAX is put together so that people can help contribute to the CSS that powers the UI? For example, where is hax-gizmo-browser or hax-manager?
4. Have you considered incorporating CKEditor for formatting blobs of text? Said another way, should blobs of text have a specific component wrapper and not be directly editable by HAX? This could solve issues like this one https://github.com/LRNWebComponents/hax-body/issues/86
5. Do you have roadmaps for HAX and/or wcfactory?
6. Do you have guidelines within your system about responsibilities of kinds components? For example types of components that are only responsible for spacing & layout, vs. those that handle typography?

Thanks!

**Comment by btopro** [comment]
Great questions. let's start to handle some of them. I pushed up some Commits that brings documentation back from the old repos (didn't realize it wasn't there so thank you).
1. Here's the docs https://github.com/elmsln/lrnwebcomponents/wiki/HAX-Schema I've also created a boilerplate / example element that's VanillaJS that should work with HAX: https://github.com/elmsln/lrnwebcomponents/tree/master/elements/example-hax-element (this was kicked out directly from the WCFactory tooling)
2. I haven't thought about modifying the page's CSS vars but that sounds like an interesting prospect. The only "style" support there is is in the advanced tab for editing an element you can mess w/ some attributes like style (obviously beyond lacking ideal). Some kind of mode or panel that has advanced CSS props that can be modified at scale, either via CSS vars or via individual tweaking like an expert mode, would be cool.
3. There is a developer deep dive which as I look at it now it's almost a year old. The fundamentals are the same even if the UI looks completely different from then https://www.youtube.com/watch?v=eGV1XWzUko8&index=42&list=PLJQupiji7J5eTqv8JFiW8SZpSeKouZACH&t=0s . I'll open a new issue to do a developer deep dive now that we're in ES modules based workflows. #105 . Also the best way in to the styling is to start poking around https://github.com/elmsln/lrnwebcomponents/blob/master/elements/hax-body/demo/index.html. The Demo links off to the elements that drive it (and this is a rather standard integration). So if you hate the top bar for example you'd look in demo, find the hax-panel (which would be in https://github.com/elmsln/lrnwebcomponents/blob/master/elements/hax-body/lib/hax-panel.js) and then start gutting away from there. The style scoping takes some getting used to and honestly a lot of the styling we have currently is in a functional prototye form (intentionally) so that we could get the big pieces working and then work backwards towards UX once we knew the capabilities were even possible :).
4. I'm not sure that we want a dedicated text editor outside of HAX. I wouldn't be entirely against it but it would be a hard sell to incorporate something massive as CKEditor into an already big footprint. The issue you expressed has been cleaned up and a lot of other contextual editing stuff has improved since then. I think so we can own the entire experience it'll be better for us to have control over the `hax-text-context.js` file which dictates how that part works.
5. Is there a visualization you think would be most useful for this? I have a general roadmap in my head but not sure the best way to get it on paper whether that be chart or table or bullet list. What do you recommend? Very quick version:
- [x] prove this is even possible
- [x] work on a flexible schema
- [x] create an appstore schema to integrate with remote sources
- [x] create initial integrations with multiple CMSs / etc
- [x] create desktop app prototype
- [x] begin getting UX feedback in production (via ELMSLN)
- [ ] convert over to ES Modules (in progress) with HAX and all other projects
- [ ] mark a full 2.0.0 release of all ES based elements and publish to webcomponents.org
- [ ] convert all integration end-points to leverage the ES modules methodology
- [ ] begin charting out ideal UX from feedback and a full on redesign:
- [ ] panel vs in context fly out needs overhauled
- [ ] add style / advanced attributes editing
- [ ] improve grid / layout capabilities
- [ ] document via a HAXCMS site
- [ ] continue building new elements based on requirements
- [ ] work on a Oauth2 broker / relationship manager that can easily slot in to broker additional appstore integrations for where things should save / query from
This is just off the top of my head for the time being. The UX stuff is a high priority after everything gets ported over and the integration points corrected (which is what we've been doing for awhile now).
WCFactory is nearly feature complete as I see it. It needs some bug fixes and testing but it basically does everything we set out for it to initially do and we are currently using it day to day.
6. Not really. We currently have nothing dictating typography for example, though documentation on some really clever global css variable "theme" layer if you will would be great as a way to help developers making elements that are HAX capable create them in such a way that they can be more visually cohesive. As for grid we have a grid-plate element which leverages:
- https://github.com/elmsln/lrnwebcomponents/tree/master/elements/grid-plate
- https://github.com/elmsln/lrnwebcomponents/tree/master/elements/responsive-grid
in order to provide the grid / container element (we refer to them as -blox in the code). Blox are just there to group things and generally we think of the page as bands of content (paragraphs-esk as far as mental model with those).

**Comment by btopro** [comment]
I've started a wiki https://github.com/elmsln/lrnwebcomponents/wiki/HAX-Schema

**Comment by starryeyez024** [comment]
Thank you for the responses and the docs!! Forgive my selfishness in not responding to the above (yet), but I wanted to capture one other question that you might have already solved for.

7.  Does HAX have a cross-site "export" feature? Hypothetical scenario is, I want to:
- Copy all the (un-upgraded) markup + content that is on haxtheweb.org
- Paste it into a page on mycoolsite.com, which is already loading all the ELMSLN javascript I need to upgrade the component markup
- Change some of the content of course, like the Jonah Hill gif will become Channing Tatum
- Save the page & publish

**Comment by btopro** [comment]
heh yes!!! :) On the demo site, click edit then Preferences and check the Developer mode and Export panel options. Then click on export. The Developer mode option also adds additional buttons to the export panel for Import so you can actually take the body content of one page and dump it in there and hit import and see an identical copy by now hax managed :)

![2018-11-21_16-57-50](https://user-images.githubusercontent.com/329735/48870417-d0ebb200-edae-11e8-80f2-44174f83d452.png)

![2018-11-21_16-59-24](https://user-images.githubusercontent.com/329735/48870418-d2b57580-edae-11e8-827a-9a4617dd7b59.png)

**Comment by btopro** [comment]
https://haxtheweb.org/hax-schema and much more docs updated. Let's file additional issues as there are more questions but I think these are all reflected in the docs of the site itself now
